export const testMovies : Array<any> = [
    {
        "tconst": "tt0002628",
        "titleType": "movie",
        "primaryTitle": "Der Andere",
        "originalTitle": "Der Andere",
        "isAdult": "0",
        "startYear": 1913,
        "endYear": "\\N",
        "runtimeMinutes": 48,
        "genres": ["Drama", "Thriller"],
        "posterPath": "https://image.tmdb.org/t/p/original/Aosrb7oQ34SjnoRyUnZ5b85djay.jpg",
        "voteAverage": 4.5,
        "voteCount": 4,
        "originalLanguage": "de",
        "overview": "When talk with friends, Dr. Hallers, a well-known lawyer in Berlin, said he was skeptical about fantasies on the split personality: he could never believe something like that. During a ride however, he has an accident, after which he often falls into a deep sleep from which he awakens with the feeling of having a dual personality. Later his double starts to rob his apartment iwith a thief. During the robbery the police arrived, arrests the thief. Hallers, having fallen asleep, wakes up without remembering anything of what happened. Eventually, the lawyer recovers and marries his fiancee.\r"
    },
    {
        "tconst": "tt0003637",
        "titleType": "movie",
        "primaryTitle": "Assunta Spina",
        "originalTitle": "Assunta Spina",
        "isAdult": "0",
        "startYear": 1915,
        "endYear": "\\N",
        "runtimeMinutes": 72,
        "genres": ["Drama"],
        "posterPath": "https://image.tmdb.org/t/p/original/cKTqxeN8H8waDbPyHB0jZVskLxD.jpg",
        "voteAverage": 6.1,
        "voteCount": 13,
        "originalLanguage": "it",
        "overview": "Assunta and Michele are in love, but others come between them. Jealousy arises. Assunta Spina stands out as an early landmark of Italian Neorealism.\r"
    },
    {
        "tconst": "tt0004003",
        "titleType": "movie",
        "primaryTitle": "Gatans barn",
        "originalTitle": "Gatans barn",
        "isAdult": "0",
        "startYear": 1914,
        "endYear": "\\N",
        "runtimeMinutes": 54,
        "genres": ["Drama"],
        "posterPath": "https://image.tmdb.org/t/p/original/nP8pC19G6HHsqfRPVNumV12VKBh.jpg",
        "voteAverage": 0,
        "voteCount": 0,
        "originalLanguage": "sv",
        "overview": "\r"
    },
    {
        "tconst": "tt0004942",
        "titleType": "movie",
        "primaryTitle": "The Battle Cry of Peace",
        "originalTitle": "The Battle Cry of Peace",
        "isAdult": "0",
        "startYear": 1915,
        "endYear": "\\N",
        "runtimeMinutes": 90,
        "genres": ["Drama"],
        "posterPath": "https://image.tmdb.org/t/p/original/sK9PeahIWs79rZpCQfKzvmPhYwJ.jpg",
        "voteAverage": 0,
        "voteCount": 0,
        "originalLanguage": "en",
        "overview": "Enemy agents under the leadership of \"Emanon\" conspire with pacifists to keep the American defense appropriations down at a time when forces of the enemy are preparing to invade. The invasion comes, and New York, Washington, and other American cities are devastated.\r"
    }
]
